services:
  - type: web
    name: voiceover-api
    env: python
    region: oregon  # or change to `frankfurt` or other available regions
    plan: free
    runtime: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PORT
        value: 10000
    build:
      pythonVersion: 3.11.9
